### ISSUE TITLE
validate on set

### ISSUE THREAD

**Issue by designermonkey** [jashkenas/backbone#3446] opened 2015-01-17 21:36 UTC
Reading an old tutorial, I see that a Model used to validate on set as well as save. I can understand why it would have been reduced to just save, but I've definitely found a case where it breaks a Model, not having it on set.

- I have a model with a defined validate function.
- I set an invalid value for a field.
- I set another invalid value for another field.
- I then validate on save.
- I now have two invalid values, and no fallback for the first set invalid value.

I like the way that the previous values are saved for fallbacks, and replaced on invalid validation, but as discovered above, it's not quite fool-proof as a system. Having validation on set is definitely fool-proof, as invalid values can't get passed over and inadvertently remain on a model.

What are your thoughts on this @jashkenas, I'd love to hear the reasoning why it was reduced to just set. As I'm learning, I've just added the following into my Model.

```js
    set: function (key, val, options) {
        // Handle both `"key", value` and `{key: value}` -style arguments.
        if (typeof key === 'object') {
            attrs = key;
            options = val;
        } else {
            (attrs = {})[key] = val;
        }

        options = _.extend({}, options, {
            validate: true
        });

        Backbone.Model.prototype.set.call(this, attrs, options);
    },
```

This overrides the behaviour, but to have to do this in every Model will get tiresome.

**Comment by platinumazure** [comment] 2015-02-10 04:16
Maybe I'm missing something here, but why not simply specify `{ validate: true }` when calling model set?

**Comment by thejameskyle** [comment] 2015-02-10 05:10
> This overrides the behaviour, but to have to do this in every Model will get tiresome.

You could also create your own base model class.

**Comment by designermonkey** [comment] 2015-02-10 09:23
So you're both saying I should, by default, put in extra leg work to fix a bug?

If the current behaviour can cause invalid data to be present, then it is a bug by design, and should be fixed, without having to rely on a developer fixing it every time they use it.

**Comment by platinumazure** [comment] 2015-02-10 14:44
It's not a bug. Disagreement about the design of a project does not automatically imply a bug.

Forcing validation every time is a breaking change and the maintainers have simply decided that this was not the direction they wanted to go. They have left it open to consumers to choose whether to validate on every set (using `{ validate: true }`) or merely on save. That allows for more flexibility.

You can argue that validation should be on by default and people should pass `{ validate: false }` to disable it during model set, but again, that's a breaking change and not something the maintainers are likely to choose to do without cutting a new release version at the very least.

**Comment by designermonkey** [comment] 2015-02-10 14:49
Then the minimum that needs to be fixed is that all previous values are saved until validation is run, so they can be correctly reset to the last valid value.

**Comment by jashkenas** [comment] 2015-02-10 15:41
> Then the minimum that needs to be fixed is that all previous values are saved until validation is run, so they can be correctly reset to the last valid value.

Yes. That sounds like an interesting idea — although one that might be trickier to figure out in practice than in theory. It would be worth exploring in a PR.

**Comment by megawac** [comment] 2015-02-10 15:53
Epitome does this by having a `options` object set on each models prototype that is merged with the options argument (breaking). Lets you do both of these

```js
let M = Backbone.Model.extend({
   options: {
       validate: true
    }
})
let m = new M;

let m = new Backbone.Model({}, {validate: true})
```

**Comment by platinumazure** [comment] 2015-02-16 23:31
> Yes. That sounds like an interesting idea — although one that might be trickier to figure out in practice than in theory. It would be worth exploring in a PR.

Hmm... Maybe that could be the beginning of a record-replay-reverse sort of thing too? Suppose this were implemented as a stack of attributes objects: each level could also have a valid metadata property to indicate if each set attempt is valid or invalid.

But that sounds a little much... I bet one of the plugins could handle this sort of thing.

**Comment by jashkenas** [comment] 2015-05-13 20:50
Seems like this conversation has run it's course. Still happy to entertain a PR that explores the notion of continuous tracking of unvalidated changes.

**Closed by jashkenas** 2015-05-13 20:50 UTC
Labels: question

**Comment by sam-at-github** [comment] 2015-05-30 06:30
> Reading an old tutorial, I see that a Model used to validate on set as well as save. I can understand why it would have been reduced to just save.

I can't understand. Efficiency? But why not have the option? i think there should be an option `alwaysValidate`. I find Model exists if and only if Model valid to be a useful and simplifying invariant. The alternative is more complex semantics, and off loading the work of handling contingencies to the client of the library.
