### ISSUE TITLE
idAttribute is undefined for modelId method if model define as function.

### ISSUE THREAD

**Issue by PavelKoroteev** [jashkenas/backbone#4230] opened 2019-12-09 12:47 UTC

**Comment by paulfalgout** [comment] 2019-12-11 07:54
I don't follow.  how is model defined as a function?

**Comment by jcbrand** [comment] 2019-12-11 08:26
I actually ran into this problem (or something similar) yesterday.

You can define a [model](https://backbonejs.org/#Collection-model) function on a collection for polymorphic model creation.

When calling `.add` on your collection, the Backbone code tries to call `.prototype.idAttribute` on the `model` attribute, but if you've defined the `model` function as a ES2015 class method then it doesn't have a `prototype` attribute.

See here: https://github.com/jashkenas/backbone/blob/75e6d0ce6394bd2b809823c7f7dc014ddb6ae287/backbone.js#L1102

So for example, this will cause the issue:

```
const Library = Backbone.Collection.extend({
    model () {
       // stuff goes here
   }
});
```

If you specify it like this, then it the problem goes away:

```
const Library = Backbone.Collection.extend({
    model: function () {
       // stuff goes here
   }
});
```

**Comment by PavelKoroteev** [comment] 2019-12-11 08:54
> I actually ran into this problem (or something similar) yesterday.
> 
> You can define a [model](https://backbonejs.org/#Collection-model) function on a collection for polymorphic model creation.
> 
> When calling `.add` on your collection, the Backbone code tries to call `.prototype.idAttribute` on the `model` attribute, but if you've defined the `model` function as a ES2015 class method then it doesn't have a `prototype` attribute.
> 
> See here:
> 
> https://github.com/jashkenas/backbone/blob/75e6d0ce6394bd2b809823c7f7dc014ddb6ae287/backbone.js#L1102
> 
> So for example, this will cause the issue:
> 
> ```
> const Library = Backbone.Collection.extend({
>     model () {
>        // stuff goes here
>    }
> });
> ```
> 
> If you specify it like this, then it the problem goes away:
> 
> ```
> const Library = Backbone.Collection.extend({
>     model: function () {
>        // stuff goes here
>    }
> });
> ```
Thank you for problem detailed description!

But your answer is not resolve problem for idAttribute.

On add new model reference not added. Therefore you cant get new model by id.

![image](https://user-images.githubusercontent.com/34572116/70605994-a0babf80-1c0c-11ea-9732-54472c0d1afc.png)

Workarond - added model.prototype.idAttribute the same as on the model.

**Comment by paulfalgout** [comment] 2019-12-11 09:02
I think the issue is that `model` on a `Collection` is defined as: `Override this property to specify the model class that the collection contains.`  This API does no support model being defined as a function.

**Comment by jaapz** [comment] 2019-12-11 09:31
@paulfalgout the backbone docs for Collection.model specify you can set a function as the `model`. That this is not possible with the `model ()` syntax (instead of `model: function()`) seems like a bug to me or at least extremely confusing.

**Comment by jcbrand** [comment] 2019-12-11 09:31
Yes, I linked to the relevant part of the docs in my original message.

See here: https://backbonejs.org/#Collection-model

**Comment by jcbrand** [comment] 2019-12-11 09:37
@PavelKoroteev: Looks like our problems are related, but not the same.

Here's what I'm talking about (pasted from the console):
```
collection = new (Backbone.Collection.extend({  model (attrs, options) { return new (Backbone.Model.extend({ idAttribute: 'customId' }))(attrs, options)}}));

child {length: 0, models: Array(0), _byId: {…}}

collection.add({ customId: 'id.1' });
backbone.js:1102 Uncaught TypeError: Cannot read property 'idAttribute' of undefined
    at child.modelId (backbone.js:1102)
    at child.get (backbone.js:997)
    at child.set (backbone.js:872)
    at child.add (backbone.js:814)
    at eval (eval at clearCache (converse-muc.js:476), <anonymous>:1:12)
    at child.clearCache (converse-muc.js:476)
    at child.restoreFromCache (converse-muc.js:425)
    at child.initialize (converse-muc.js:396)
    at child.Backbone.Model (backbone.js:410)
    at child [as constructor] (backbone.js:2060)
    at child [as constructor] (backbone.js:2060)
    at new child (backbone.js:2060)
    at wrappedOverride.model (converse-muc.js:95)
    at new wrappedOverride (pluggable.js:71)
    at wrapper.<anonymous> (_createCtor.js:25)
    at apply (_apply.js:18)
    at new wrapper (_createPartial.js:38)
    at child._prepareModel (backbone.js:1137)
    at child.set (backbone.js:889)
    at Object.options.success (backbone.js:1059)
    at child.localSync (backbone.browserStorage.js:120)
```

**Comment by paulfalgout** [comment] 2019-12-11 12:29
I think the issue is actually the same.  And also the same as https://github.com/jashkenas/backbone/issues/4203

using `model: function(attrs, options)` would create a prototype which would not have `idAttribute` and it would fall back to `id` so it would "work"

You're correct the polymorphic model is documented.  _but_...   it hasn't supported `idAttribute` or es6-type methods because of this line with `model.prototype` for quite a while.

It seems https://github.com/jashkenas/backbone/pull/3966 is a fix of sorts  :-/

**Comment by jcbrand** [comment] 2019-12-11 15:02
Seeing a PR from 2016 languishing and not getting merged (or rejected in favour of something better) basically discourages me from even trying to make a PR to fix this issue.

From what I can tell, Backbone is pretty much dead.

Like others have done as well, I've created a fork called [Skeletor](https://github.com/skeletorjs/skeletor) which I'll use to update my Backbone code to more modern APIs and standards and then I'll gradually move away to something better.

**Comment by jashkenas** [comment] 2019-12-13 19:42
I just merged the old https://github.com/jashkenas/backbone/pull/3966 PR, after resolving conflicts. Let me know if it gives you any trouble...

**Closed** 2022-01-07 02:26 UTC
Labels: duplicate
