### ISSUE TITLE
Problem when Model and Collection each have "parse" methods.

### ISSUE THREAD

**Issue by i-am-al-x** [jashkenas/backbone#4035] opened 2016-05-27 18:01 UTC
SUBJECT: Problem when Model and Collection each have "parse" methods.

By Alexander Danel
2016-May-27

When both "Collection" and its underlying "Model" each have their own "parse" 
method defined, an attempt to do "collection.fetch()" causes a problem.
The retrieved data is processed first by "collection.parse()",
and then a little bit later the processed data is passed to 
"model.parse()", but the second parse fails, because the data
is cooked, not raw.

The reason to have a "parse" method on the Model is because I do sometimes
instantiate the Model as a singleton, not just as a member of the collection.
In other words, although the model gets instantiated automatically by the
collection in some parts of my program, I also want to sometimes manually
instantiate it.  (Automatic bulk instantiations versus manual singleton
instantiations.)

The workaround, for me, I suppose, is to define two different Model classes 
that are otherwise identical except that one would have "parse" and the other 
would not.  But, that's not elegant.  The intention is that they should both
the bulk and singleton instantiations should be of one class.

PROPOSAL: It is my understanding that the "options" to an instantiation can 
include a value for "parse" that is true/false.   Therefore, I suggest that
this option be used when the Collection instantiates a Model, temporarily
setting "parse:false".

I am on Mac OS, working in Chrome, using the following backbone version:

`// Current version of the library. Keep in sync with package.json 
     Backbone.VERSION = 1.2.3;
`

(Note: I am attempting to use the "insert code" feature on this site, but when I switch to "preview", the results don't look like code.  Perhaps because I'm on a Mac, using Safari?  Therefore, I will also attempt to drop a text file into this message.)
[a-danel-backbone-disfunction.txt](https://github.com/jashkenas/backbone/files/287126/a-danel-backbone-disfunction.txt)

At the time when the problem manifests, my stack-trace is this:

`parseCtApiResponse      cti-models.js:  23
    Backbone.Model          backbone.js:    398
    child               backbone.js:    1850
    _prepareModel           backbone.js:    1087
    set             backbone.js:    868
    options.success         backbone.js:    1024
    fire                jquery-2.2.0.js:    3182
    ...etc...
`

`//------------------------------------------------------------------------------
// Stack trace with surrounding code.
//------------------------------------------------------------------------------
//  Backbone.Model          backbone.js:    398
//
  var Model = Backbone.Model = function(attributes, options) {
    var attrs = attributes || {};
    options || (options = {});
    this.cid = _.uniqueId(this.cidPrefix);
    this.attributes = {};
    if (options.collection) this.collection = options.collection;
HERE ==>
    if (options.parse) attrs = this.parse(attrs, options) || {};
<== HERE
    attrs = _.defaults({}, attrs, _.result(this, 'defaults'));
    this.set(attrs, options);
    this.changed = {};
    this.initialize.apply(this, arguments);
  };

//------------------------------------------------------------------------------
//  child               backbone.js:    850
//
  var extend = function(protoProps, staticProps) {
    var parent = this;
    var child;

```
// The constructor function for the new subclass is either defined by you
// (the "constructor" property in your `extend` definition), or defaulted
// by us to simply call the parent constructor.
if (protoProps && _.has(protoProps, 'constructor')) {
  child = protoProps.constructor;
} else {
```

HERE ==>
      child = function(){ return parent.apply(this, arguments); };
<== HERE
    }

//------------------------------------------------------------------------------
//  _prepareModel           backbone.js:    1087
//
    _prepareModel: function(attrs, options) {
      if (this._isModel(attrs)) {
        if (!attrs.collection) attrs.collection = this;
        return attrs;
      }
      options = options ? _.clone(options) : {};
      options.collection = this;
HERE ==>
      var model = new this.model(attrs, options);
<== HERE
      if (!model.validationError) return model;
      this.trigger('invalid', this, model.validationError, options);
      return false;
    },

//------------------------------------------------------------------------------
//  set             backbone.js:    868
//
        // If this is a new, valid model, push it to the `toAdd` list.
        } else if (add) {
HERE ==>
          model = models[i] = this._prepareModel(model, options);
<== HERE
          if (model) {
            toAdd.push(model);
            this._addReference(model, options);
            modelMap[model.cid] = true;
            set.push(model);
          }
        }

//------------------------------------------------------------------------------
//  options.success         backbone.js:    1024
//
    fetch: function(options) {
      options = _.extend({parse: true}, options);
      var success = options.success;
      var collection = this;
      options.success = function(resp) {
        var method = options.reset ? 'reset' : 'set';
HERE ==>
        collection[method](resp, options);
<== HERE
        if (success) success.call(options.context, collection, resp, options);
        collection.trigger('sync', collection, resp, options);
      };
      wrapError(this, options);
      return this.sync('read', this, options);
    },

//------------------------------------------------------------------------------
`

**Comment by relativityboy** [comment] 2016-05-28 17:35
You could create your own parse() that detects the cooked/uncooked nature of the data being passed to it. 

IMHO temporarily flipping values in the middle of an operation is a recipe for bugs down the line.

**Comment by AL-X-dev** [comment] 2016-05-29 13:36
Firstly, let me congratulate Jeremy Ashkenazi and the team for the existence of Backbone; it is quite an achievement.  That said, let's get down to business.  This issue concerns the fact that a problem occurs when "parse" is defined at both the Model and Collection levels.

Under what conditions is the current behavior not a bug?  Is it ever correct to parse a message twice? Or does the current behavior rely upon one of two extremes: either the accident of a programmer not defining a parse at both levels, or a programmer's extraordinary awareness of writing special detection code in order enable a parse in both places?

I do understand that the parse always has to be a little different at Model level versus Collection, the difference between a single value and an array of values.  But as a programmer, the only way I will ever come to the conclusion that I should do as you suggest, (write custom code to detect data is already parsed,) is by running into a problem and then debugging the problem.  Having a message parsed twice is simply not the expected behavior.

I'm puzzled that you say "flipping values in the middle of an operation is a recipe for bugs down the line."  I have read the Backbone code; it is replete with snippets of code that look like this:

    options = _.extend({parse:false},options);

By the way, what is "IMHO"?

Alexander

**Comment by pmalouin** [comment] 2016-05-30 18:17
You could check if the current model instance is part of a collection by checking `this.collection` within the `parse` method:

```
  parse : function(response) {
    if (this.collection) {
      // Do not parse a second time
      return response;
    } else {
      // Do the parsing logic.
    }
  }
```

**Comment by AL-X-dev** [comment] 2016-05-31 16:38
pmalouin: "You could check if the current model instance is part of a collection..."

Yes, I could do that, and yes, there is some cleverness to this idea, but no, it is not without fault, and no, it is not a satisfactory solution.

Checking whether an instance is assigned to a collection does solve the problem as I originally stated it, but it does not solve the larger problem.  My original statement was that I have a Class from which I manually instantiate a singleton, but also auto-instantiate collection members.  It is always the case in any Backbone application that a collection needs a parse that is different than the singleton parse; that is why both the Collection class and the Model class each have a "parse" method defined and called.

My current workaround is that I create a Model class for use with the collection, and then a derivative Model class for use with the singletons.

    ModelClassWithoutParse  =  Backbone.Model.extend(...);

    ModelClassForSingletons  = ModelClassWithoutParse.extend(...,{parse:function(){...}});

    MyCollectionClass           = Backbone.Collection.extend(...,{model:ModelClassWithoutParse});

My first problem with this is: I shouldn't need to do it.  

My second problem with my workaround can be found by examining the solution proposed by "pmalouin".  He builds upon a prior proposal that it should be the responsibility of the "model.parse" method to determine whether or not it should have been called, and take action only after determining that it was not called in error.  He suggests that this determination can be made by checking for "model.collection."  At first blush, this suggestion seems to make sense, since a model instance that is auto-instantiated by a Collection will always have "model.collection" set, and a manually instantiated singleton will not.  But I doubt that such segregation can be (effortlessly) guaranteed, and the inability to guarantee such segregation also works against my work-around.

The technique of examining "model.collection" assumes that the static structure tells us about dynamic usage.  Maybe in a strongly typed language it could, but in this case, I doubt it.  Backbone allows me to manually instantiate a model, and then add it to a collection.  This kills my work-around, but not yet pmalouin's.  But Backbone also allows a model that is already within a collection to be used outside of that collection.  Suppose I take an individual model and send it to the server for an "update" as a singleton; doesn't the server send back something that would be subject to "parse"?  If so, then the appropriate parse would be that for a singleton, not a collection.

I have read the Backbone code.  It is clear that a model instance can be a member of more than one collection.  Does it not, therefore follow, that a model instance can be a member of a collection but also used in a different context where it is considered a singleton?

The whole discussion seems silly to me.  From my view, the following two points are clear:

(1) Parsing twice is nobody's intention; it is a bug.
(2) A simple solution exits, and the solution breaks nothing.

The simple solution requires only that you follow the pattern of so much other Backbone code and create a scoped (and therefore temporary) version of the "options" object; so that this scoped "options" can be used to turn off the downstream parse.  So, after "collection.parse" has completed, just do:

    options = _.extend(options,{parse:false});

Not a big deal.

Alexander

**Comment by relativityboy** [comment] 2016-05-31 18:28
You could very easily extend Backbone.Collection to do just that, and then extend all your collections.

I actually have my own root .View .Model and .Collection objects (not classes, Javascript doesn't have classes) that I use to start most projects. They have custom setters & constructors, handle parents and do all kinds of automagical things that makes life much easier for me. It would be nice if Backbone did it for me, but not everyone needs what I need, and some solutions (like one you propose) COULD break other people's code (all the people who've been using .parse as it's implemented today).

I'd suggest trying your own root Collection, and if you find something that really works well for you, make a branch and rewrite the code so no tests are broken, Then make a pull-request with your solution and see what everyone thinks!

**Comment by AL-X-dev** [comment] 2016-06-01 01:18
> ... Javascript doesn't have classes

I'm taking a linguistic shortcut, it's just easier to say "Class" than "function having a name that starts with a capital letter, intended as a constructor, with members added to a prototype, etc."  I find it difficult to describe what I'm thinking without allowing myself the luxury of using the word "Class" in that  way.  Luckily for me, ECMA-6 makes the word "Class" official:  

    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

> . . . COULD break other people's code ...

Yes, I'll concede that it could.  But with my limited imagination, I can come up with only one such case, and it would be really, really weird.  First, here are some common use cases I that don't get broken.  

(1) Server sends singleton as JSON object (no wrapper), collection as array of such objects.  In that case, no parse function is needed at either level.

(2) Server sends singleton with a wrapper, one member of which is named "data" which is the JSON object.  Server sends collection with a wrapper, one member of which is named "data" which is an array of JSON objects.  This is my case.  I need one "parse" function for the Model, to extract the object, and a different "parse" function for the Collection, to extract the array of objects.  Once I have the array, my data is no longer wrapped; (it is fully cooked, nothing is raw.)  This perfectly ordinary case gets broken now.

And now the use case that would get broken by my proposed fix:

(3) Server sends Collection as something that holds an array of wrapped objects, where the individual items in the array, i.e the rows, each has a wrapper that must be removed by the Model.parse function.

Use case (3) seems really weird and unlikely to me.  Can anyone come up with a scenario where the server would want to go through the trouble of wrapping row items?  Rows don't get success codes -- queries do; by which I mean that when it is returning a collection, the server has no reason to embellish the individual items with a wrapper.  And how would the programmer who created this system even get the idea that such behavior will work?  The double parse behavior is not documented, and programmers like I discover it only when our parse fails and we debug the issue.

> . . . make a pull-request . . .

I've never done that.  Don't you think it will look odd for me to make a Pull requests just to get a one-line change?  I'm not familiar with the culture.

Thank you for the feedback. 

Alexander

**Comment by paulfalgout** [comment] 2016-06-01 01:33
> Don't you think it will look odd for me to make a Pull requests just to get a one-line change

I'd say that's a perfect reason to make a pull request.

**Comment by prantlf** [comment] 2017-06-15 20:29
@AL-X-dev, you should divide the parsing code to the collection-specific part and the model-specific part. There is nothing like double-parsing as you write.

The task for the {collection.parse} is to create an array of objects from the server response. Only breaking down the response; not going lower and "massaging" the objects for future models. Every single object in the array is supposed to be parsed later by the {model.parse}.

The task for the {model.parse} is to create an object of attributes as the model's interface should expose them.

I use this principle to support responses of REST APIs getting a collection of objects (/nodes/{id}/nodes) and a single object (/nodes/{id}). Using the same `parse:true` option for both collection and model is an essential feature of Backbone parsing. It would break my code.

**Comment by Upperstage** [comment] 2018-01-07 17:14
Any idea why my model.parse IS NOT called when I do a collection.fetch? Everywhere I read it should be called, but it is not.

**Comment by jolmg** [comment] 2021-06-24 01:08
> The task for the `collection.parse` is to create an array of objects from the server response. Only breaking down the response; not going lower and "massaging" the objects for future models. Every single object in the array is supposed to be parsed later by the `model.parse`.

@prantlf, you've assumed that "going lower and 'massaging' the objects" is the problem when it might not even occur at all.

For example, in my case, my responses are of the form `{data: x, <response-metadata-fields>}`, where `x` is either the attributes of a single model or an array of such attributes. Both `Model`'s and `Collection`'s `parse` are set to return `.data` in accordance to Backbone's documentation, which says that `Collection.prototype.parse` should "return the array of model attributes".

Since it passes that array of attributes to `Model.prototype.parse` which is documented to take "the raw response object", the documentation seems currently wrong and should instead say that `Collection.prototype.parse` should return an array of raw-response-looking objects.

**Comment by prantlf** [comment] 2021-06-24 10:47
Yes, @jolmg, I implemented the `parse` method as you would describe it:

> `Collection.prototype.parse` should return an array of raw-response-looking objects.

But it is just one of the two possibilities how to deal with this. Backbone passes `{ parse: true }` from `fetch` to collection's `set`/`reset`, which propagates it to models' constructors. It means that both collection's and models' `parse` methods will be called. If you want to comply with this, you will need to either divide the parsing work to collection and model parts as I did, of you will have to recognise an already parsed object with model attributes in a model's `parse` method. which is your case.

The documentation should mention, that both collection's and models' `parse` methods will be called when fetching a collection:

> `Model.prototype.parse` will be called for the items of the array returned by `Collection.prototype.parse`.

I am not sure if it should assume what you need to return. It might be too much, because it depends on how you implement the `parse` methods and that depends on your REST API design.

For example, there are applications that fetch only collections. They may decide not to implement model's `parse` at all. Only applications that use models that are fetchable separately too, will have to deal with this problem.

In your case the collection response looks like this:

    {
      data: [
        { id: 1, name: 'Test', ... },
        { id: 2, name: 'Test2', ... }
      ],
      <response-metadata-fields>}
    }

and a single model response looks like this:

    {
      data: { id: 1, name" 'Test', ... },
      <response-metadata-fields>}
    }

It means that your `Collection.prototype.parse` would be beautiful:

    return response.data

and your `Model.prototype.parse` would be ugly:

    if (response.data or response.a-metadata-field) {
      return massage(response.data)
    } else {
      return massage(response)
    }

A variation on the same theme would be a `Collection.prototype.parse` that would "bloat" the items in the array to look like single model responses:

    return response.data.map(item => { data: item, <response-metadata-fields> })

The `Model.prototype.parse` would be always processing raw responses then:

    return massage(response.data)

**I think that improving the documentation in this area is a good idea. This is a design issue and as such it cannot be just fixed as a bug in the implementation, because it would break the existing code.**

As a solution in Backbone, there could an additional option added for module parsing, for example:

    { parse: true, parseModels: true }

The `parseModels` would be used in `_prepareModel` as `parse` for the model. Then a discussion about the default value could follow. But I am probably going to far here. Backbone is a mature library and long-term maintainers of complex Backbone applications know it down to the last line of code. This might confuse the newcomers, hence the hint for the documentation.

**Comment by jgonggrijp** [comment] 2021-12-20 17:52
https://github.com/jashkenas/backbone/issues/4035#issuecomment-222537061, https://github.com/jashkenas/backbone/issues/4035#issuecomment-222777545, https://github.com/jashkenas/backbone/issues/4035#issuecomment-308857020 are spot on.

> (...) Or does the current behavior rely upon one of two extremes: either the accident of a programmer not defining a parse at both levels, or a programmer's extraordinary awareness of writing special detection code in order enable a parse in both places?

Taking into account that your code might run in multiple scenarios does not require "extraordinary awareness", to the contrary. It is an essential part of programming. Failing to take this into account invariably means writing code with bugs in it.

**Closed by jgonggrijp** 2021-12-20 17:52 UTC
