### ISSUE TITLE
views: events getting called before initialize in  1.2.*?

### ISSUE THREAD

**Issue by builtbylane** [jashkenas/backbone#3704] opened 2015-07-07 16:26 UTC
just updated backbone to  1.2.* from 1.1.2 and I'm running into an issue in my views where the `events` block is being called before the `initialize` block. Was this an intentional change? I didn't see this in the changelog.

Had to lock into 1.1.2 since this change is breaking my app. (I conditionally extend the events hash depending on  options set within the initialize block.)

**Comment by jridgewell** [comment] 2015-07-07 17:46
Dupe of #3620. Documentation was added in #3640:

> Views now always delegate their events in `setElement`. You can no longer modify the events hash or your view's `el` property in `initialize`.

**Closed by jridgewell** 2015-07-07 17:46 UTC

**Comment by akre54** [comment] 2015-07-07 18:48
Turn your events hash into a method or use `delegate` in your initialize method.

**Comment by builtbylane** [comment] 2015-07-08 17:47
so turn it into a method and call it from `initialize`?

**Comment by jridgewell** [comment] 2015-07-08 18:00
No, you can either turn `events` into a method, or call `#delgate` in `#initialize`:

```js
var View = Backbone.View.extend({
  events: function() {
    return {
      'click span': 'onClickSpan',
      'click': 'onClick'
    };
  }
});

// OR

var View = Backbone.View.extend({
  initialize: function() {
    this.delegate('click', 'span', this.onClickSpan);
    this.delegate('click', this.onClick);
  }
});
```

**Comment by builtbylane** [comment] 2015-07-09 18:55
thank @jridgewell  @akre54. So I've been doing that, but I was relying on initialize being called before the events method:
```
var View = Backbone.View.extend({
  events: function() {
    var eventsHash = {};
    if (this.doClickSpan) {
      _.extend(eventsHash, { 
        'click span' : 'onClickSpan'
      });
    }
    return eventsHash;
  },
  initialize: function(opts) {
    var o = opts || {};
    this.doClickSpan = o.doClickSpan
  }
});

new View({doClickSpan: true});
```
this pattern no longer works in Backbone 1.2.*

**Comment by builtbylane** [comment] 2015-08-18 21:13
@jridgewell, sorry to be a nuisance, but what was the motivation for making these  changes?

**Comment by jridgewell** [comment] 2015-08-18 21:20
See https://github.com/jashkenas/backbone/pull/3060#issue-29326609.
