### ISSUE TITLE
model returns undefined while iterating although it exists in Collection

### ISSUE THREAD

**Issue by siddo420** [jashkenas/backbone#3744] opened 2015-08-05 17:13 UTC
I have a weird issue bothering me atm.  

I am on BB 1.2.1 and for some reason I see "undefined" as model value for one of my models while iterating through the models Collection. Please note that its always the model that was assigned values using 'defaults()' method.

I have confirmed using toJSON() and .model property that the model does exist in Collection.

Defaults method:
```
, defaults: function(){
  return {id:1, iconName:'icon-pages', firstName:'Sido', unread: 2, lastName:'1'};
} // eof defaults()
```

Here is how I am adding models to collection:

```
collection.add( new Model({ id:2, firstName:'Sido', iconName:'icon-gear', unread:1, lastName:'595' }));
collection.add( new Model()); // should use default model values
collection.add( new Model({ id:3, firstName:'Sido', iconName:'icon-gear', unread:9,lastName:'696' }));
```

Confirmation of model values using toJSON():
```
[{"id":2,"firstName":"Sido","iconName":"icon-gear","unread":1,"lastName":"595"},{"id":1,"iconName":"icon-pages","firstName":"Sido","unread":2,"lastName":"1"},{"id":3,"firstName":"Sido","iconName":"icon-gear","unread":9,"lastName":"696"}]
```

As you can see (from above) the default model does exist in collection. However, when I iterate over the collection to remove all models I get undefined for the default mode (id=1) only.
Here is the code:
```
console.log( JSON.stringify(collection.toJSON())); // result above
collection.each( function( model ){
  console.log( "Removing model from collection to free up mem: " + JSON.stringify( model ));
  collection.remove( model );				
}); //eof each
```

Here is the result of console.log inside each() above:
```
Removing model from collection to free up mem: {"id":2,"firstName":"Sido","iconName":"icon-gear","unread":1,"lastName":"595"}
Removing model from collection to free up mem: {"id":3,"firstName":"Sido","iconName":"icon-gear","unread":9,"lastName":"696"}
Removing model from collection to free up mem: undefined
```

**Comment by jridgewell** [comment] 2015-08-05 17:18
Dupe of https://github.com/jashkenas/backbone/issues/3534, fix in https://github.com/jashkenas/backbone/pull/3649.

It's because you're mutating an array as you're iterating it.

**Comment by jridgewell** [comment] 2015-08-05 17:19
Can someone tag this issue, I'm on my phone...

**Closed by jridgewell** 2015-08-05 17:18 UTC
