### ISSUE TITLE
Collection#fetch wrongly populates the _byId property in subsequent fetches

### ISSUE THREAD

**Issue by kucharskimaciej** [jashkenas/backbone#3638] opened 2015-05-27 09:55 UTC
I found this issue while investigating why my Collection#get didn't work half of the time.
I'm fetching the collection from iTunes and I need to use parse both the collection and each model. First fetch (empty collection) works fine, those are keys of the Collection._byId object:
```
["392612116", "395544690", "429223235", "434215319", "493267725", "704239726", "763690325", "887944575", "982732058", "994873600", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10"]
```
As you can see the models are referenced by both the `id` and the `cid` property. It also indicates that  Model#parse was called before the Collection#_addReference, which is the expected behaviour.

After fetching the collection second time (no options passed) the Collection._byId is:
```
["c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10"]
```
So basically just `cid`s and no `id`.

After some investigation I'm assuming that the problem is in the Collection#set method that marks models as duplicate/nonexistent based on the presence of `id` attribute in `attrs` variable:

```
if (attrs instanceof Model) {
          id = model = attrs;
        } else {
          id = attrs[targetModel.prototype.idAttribute || 'id'];
        }
```
The thing is that attrs have not been parsed by the Model#parse method so the `id` might not exist yet (in my case it doesn't).

The models are later considered nonexistent because of that and removed:
```
// Remove nonexistent models if appropriate.
      if (remove) {
        for (i = 0, l = this.length; i < l; ++i) {
          if (!modelMap[(model = this.models[i]).cid]) toRemove.push(model);
        }
        if (toRemove.length) this.remove(toRemove, options);
      }
```

Possible fixes might include instantinating the `targetModel` class (or calling it's parse) with `attrs` (for which I'll include pull request later) or mentioning in documentation that the Model#parse method should not touch the `id`.

**Comment by jridgewell** [comment] 2015-05-27 15:51
Thanks for the write up!

I'm taking a look into it. Just to make sure I'm on the right track, could you also post a small [jsFiddle](https://jsfiddle.net/) that shows the issue?

**Comment by kucharskimaciej** [comment] 2015-05-27 22:06
Justin,
here's the https://jsfiddle.net/dvx3at16 . You will probably need to run this code locally though, or use some plugin for CORS. Let me quickly explain what's going on there. The `id` attribute for the model is created in `parse` method. I'm then fetching the collection twice. Notice that the first time the `_byId` property contains 20 keys - 10 ids and 10 cids, which is expected. The second time, there are only 10 keys - just the cids.

**Comment by jridgewell** [comment] 2015-05-28 02:11
After looking into it, this is a dupe of #3529. I know that this particular problem can be resolved by setting `Book#idAttribute`:

```js
var Book = Backbone.Model.extend({
    idAttribute: 'trackId',
    parse: function(attrs) {
        return {
            id: attrs.trackId,
            title: attrs.trackName,
            author: attrs.artistName,
            description: attrs.description,
            picture: attrs.artworkUrl100,
            price: attrs.price,
            ISBN: "N/A"
        };
    }
});
```

**Closed by jridgewell** 2015-05-28 02:11 UTC

**Comment by kucharskimaciej** [comment] 2015-05-28 07:21
It may be worth mentioning in the documentation of the `parse` method, even more so if there are other issues related to the same underlying cause (like the #3529 )
