### ISSUE TITLE
API of 'on' function does have not backward compatible changes

### ISSUE THREAD

**Issue by fedulovivan** [jashkenas/backbone#3621] opened 2015-05-21 13:04 UTC
Previously this way of defining events as map and passing context worked fine:
```javascript
someview.on({
  one: one,
  two: two
}, this);
```

After upgrading to 1.2.0 we need to set second argument to undefined and define context as third:
```javascript
someview.on({
  one: one,
  two: two
}, void 0, this);

**Comment by jridgewell** [comment] 2015-05-21 14:17
Dupe of #3603.

**Closed by jridgewell** 2015-05-21 14:17 UTC
