### ISSUE TITLE
Manually triggering event on model that is part of collection causes error

### ISSUE THREAD

**Issue by QuotableWater7** [jashkenas/backbone#3717] opened 2015-07-16 23:53 UTC
Hello -- we were upgrading backbone in our app and ran into an unexpected error.  Here is the simplest repro for it:
```
var c = new Backbone.Collection();
var m = new Backbone.Model();

c.add(m);
m.trigger('change');  //  error thrown
```
Was there an intentional change in how events are handled?

Thanks!

**Comment by megawac** [comment] 2015-07-16 23:57
@QuotableWater7, you're clashing with the `change` event in `Backbone` which expects the format `trigger('change', model, options)`. Do `trigger('change', m)` and it should work as expected

**Comment by QuotableWater7** [comment] 2015-07-17 00:00
Can we update the docs?  This was a change in behavior and docs do not mention that models are now a required param

**Comment by megawac** [comment] 2015-07-17 00:02
You're correct, this is a regression from `1.1.2`

**Comment by QuotableWater7** [comment] 2015-07-17 00:04
@megawac also worth noting here, you can `trigger` without passing a model so long as the model isn't part of a collection

**Comment by megawac** [comment] 2015-07-17 00:13
Yeah, this is due to this change

**Comment by jridgewell** [comment] 2015-07-17 00:14
Dupe of https://github.com/jashkenas/backbone/issues/3662

**Comment by jares777** [comment] 2015-08-15 18:29
The documentation says
**trigger**
object.trigger(event, [*args])
Trigger callbacks for the given event, or space-delimited list of events. Subsequent arguments to trigger will be passed along to the event callbacks.

It doesn't specifically says you have to use model.trigger('change', model);

This is caused by line number 3 which needs **&& model** in the if condition :
```javascript
_onModelEvent: function(event, model, collection, options) {
      if ((event === 'add' || event === 'remove') && collection !== this) return;
      if (event === 'destroy') this.remove(model, options);
      if (event === 'change' ) {
        var prevId = this.modelId(model.previousAttributes());
        var id = this.modelId(model.attributes);
        if (prevId !== id) {
          if (prevId != null) delete this._byId[prevId];
          if (id != null) this._byId[id] = model;
        }
      }
      this.trigger.apply(this, arguments);
    }
```

**Closed** 2015-10-26 19:18 UTC
Labels: bug
