### ISSUE TITLE
Collection's _byId hash out of sync when removing models

### ISSUE THREAD

**Issue by berniegp** [jashkenas/backbone#3801] opened 2015-09-23 14:54 UTC
`Collection._removeModels` does the following:

```
_removeModels: function(models, options) {
  var removed = [];
  for (var i = 0; i < models.length; i++) {
    var model = this.get(models[i]);     // [cb-0]
    if (!model) continue;

    var index = this.indexOf(model);     // [cb-1]
    this.models.splice(index, 1);            // [1]
    this.length--;

    if (!options.silent) {
      options.index = index;
      model.trigger('remove', model, this, options);   // [2] 
    }

    removed.push(model);
    this._removeReference(model, options);  // [3]
  }
  return removed.length ? removed : false;
},
```

[1] updates the collection.models, removing a model
[2] the `remove` event is emitted
[3] collection._byId mapping of "model id" to model is updated

During [2], collection._byId is out of sync with collection.models. This is a problem if a `remove` listener tries to remove the same model currently being removed from the collection. In that case, this occurs:

[cb-0] `this.get(models[i])` uses collection._byId and determines that the model is in fact in the collection
[cb-1] `this.indexOf(model)` returns -1 so the following splice clobbers the model array.

**Comment by jridgewell** [comment] 2015-09-23 14:58
Thanks for the write up. This looks to be a duplicate of https://github.com/jashkenas/backbone/issues/3693, though.

**Closed by jridgewell** 2015-09-23 14:58 UTC

**Comment by berniegp** [comment] 2015-09-23 15:03
Sorry about that. I missed that one!
