### ISSUE TITLE
Collection set method going into merge with same models/objects already present

### ISSUE THREAD

**Issue by elgubenis** [jashkenas/backbone#3708] opened 2015-07-13 03:33 UTC
```js
var collection = new Backbone.Collection([{id: 1}, {id: 2}]);
collection.set([{id: 1}, {id: 2}]);
```

This code will enter the merging process of the 2 already existing models, im not sure if thats right, because no change of attributes will happen.

Instantiating a new collection with an array of objects creates a model for every object, but the 'merge-check' in backbone is comparing against bare attributes if no models (but an array of objects is) added on the set-method.
Though it says "// Turn bare objects into model references, ...", but i can't spot where the bare object is turned into a model reference (for comparing if there is a need to merge)

```js
if (merge && attrs !== existing) {
```
from
```js
      // Turn bare objects into model references, and prevent invalid models
      // from being added.
      for (var i = 0; i < models.length; i++) {
        attrs = models[i];

        // If a duplicate is found, prevent it from being added and
        // optionally merge it into the existing model.
        if (existing = this.get(attrs)) {
          if (remove) modelMap[existing.cid] = true;
          if (merge && attrs !== existing) {
            attrs = this._isModel(attrs) ? attrs.attributes : attrs;
            if (options.parse) attrs = existing.parse(attrs, options);
            existing.set(attrs, options);
            if (sortable && !sort && existing.hasChanged(sortAttr)) sort = true;
          }
          models[i] = existing;

        // If this is a new, valid model, push it to the `toAdd` list.
        } else if (add) {
          model = models[i] = this._prepareModel(attrs, options);
          if (!model) continue;
          toAdd.push(model);
          this._addReference(model, options);
        }
```

If the existing piece of code is correct as is, could someone point out the reason why?

**Comment by elgubenis** [comment] 2015-07-13 03:46
as far as I understand, we would get false here:
```javascript
attrs !== existing
```
because:
```javascript
{ a: 1 } != { a: 1 }
// and
{ a: 1, b: 1} != { b: 1, a: 1 }
```

**Comment by elgubenis** [comment] 2015-07-13 03:53
I am already preparing some PR, but maybe thats not necessary because there is just some explanation missing for me to understand why thats done like that.

**Comment by elgubenis** [comment] 2015-07-13 03:59
As im thinking, that might be the reason why the merge switch exists for the options, but i think that even when merging is desired that there are some models which dont need any merging because they are exactly alike.

**Comment by jridgewell** [comment] 2015-07-13 04:05
I'm unsure what the problem is?

**Comment by elgubenis** [comment] 2015-07-13 04:15
lets suppose that a .set is called with an array of 100 objects. 50 objects already exist exactlty alike but as a model instance.

problems:
1. (overhead) 50 objects would get merged into 50 models which are already alike (dont need to get merged)
2. adding feedback/resume to the update event (see #3700) including mergedModels would return that there was a merge done on 50 models which were already alike.

im working on a PR which includes the update event triggering and sending the previous/removed Models, addedModels and mergedModels.

**Comment by elgubenis** [comment] 2015-07-13 04:17
```javascript
set: function(models, options) {
      options = _.defaults({}, options, setOptions);
      if (options.parse && !this._isModel(models)) models = this.parse(models, options);
      var singular = !_.isArray(models);
      models = singular ? (models ? [models] : []) : models.slice();
      var id, model, attrs, existing, sort;
      var at = options.at;
      if (at != null) at = +at;
      if (at < 0) at += this.length + 1;
      var sortable = this.comparator && (at == null) && options.sort !== false;
      var sortAttr = _.isString(this.comparator) ? this.comparator : null;
      var toAdd = [], toRemove = [], modelMap = {}, previousModels = [], mergedModels = [];
      var add = options.add, merge = options.merge, remove = options.remove;
      var order = !sortable && add && remove ? [] : false;
      var orderChanged = false;

      // Turn bare objects into model references, and prevent invalid models
      // from being added.
      for (var i = 0; i < models.length; i++) {
        attrs = models[i];

        // If a duplicate is found, prevent it from being added and
        // optionally merge it into the existing model.
        if (existing = this.get(attrs)) {
          if (remove) modelMap[existing.cid] = true;
          if (merge && attrs !== existing) {
            attrs = this._isModel(attrs) ? attrs.attributes : attrs;
            if (options.parse) attrs = existing.parse(attrs, options);
            existing.set(attrs, options);
            if (sortable && !sort && existing.hasChanged(sortAttr)) sort = true;
            mergedModels.push(existing);
          }
          models[i] = existing;

        // If this is a new, valid model, push it to the `toAdd` list.
        } else if (add) {
          model = models[i] = this._prepareModel(attrs, options);
          if (!model) continue;
          toAdd.push(model);
          this._addReference(model, options);
        }

        // Do not add multiple models with the same `id`.
        model = existing || model;
        if (!model) continue;
        id = this.modelId(model.attributes);
        if (order && (model.isNew() || !modelMap[id])) {
          order.push(model);

          // Check to see if this is actually a new model at this index.
          orderChanged = orderChanged || !this.models[i] || model.cid !== this.models[i].cid;
        }

        modelMap[id] = true;
      }

      // Remove stale models.
      if (remove) {
        for (var i = 0; i < this.length; i++) {
          if (!modelMap[(model = this.models[i]).cid]) toRemove.push(model);
        }
        if (toRemove.length) previousModels = this._removeModels(toRemove, options);
      }

      // See if sorting is needed, update `length` and splice in new models.
      if (toAdd.length || orderChanged) {
        if (sortable) sort = true;
        this.length += toAdd.length;
        if (at != null) {
          for (var i = 0; i < toAdd.length; i++) {
            this.models.splice(at + i, 0, toAdd[i]);
          }
        } else {
          if (order) this.models.length = 0;
          var orderedModels = order || toAdd;
          for (var i = 0; i < orderedModels.length; i++) {
            this.models.push(orderedModels[i]);
          }
        }
      }

      // Silently sort the collection if appropriate.
      if (sort) this.sort({silent: true});

      // Unless silenced, it's time to fire all appropriate add/update/sort events.
      if (!options.silent) {
        var addOpts = at != null ? _.clone(options) : options;
        for (var i = 0; i < toAdd.length; i++) {
          if (at != null) addOpts.index = at + i;
          (model = toAdd[i]).trigger('add', model, this, addOpts);
        }
        if (toAdd.length || previousModels.length || mergedModels.length) {
          if (toAdd.length) options.addedModels = toAdd;
          if (previousModels.length) options.previousModels = previousModels;
          if (mergedModels.length) options.mergedModels = mergedModels;
          this.trigger('update', this, options);
        }
        if (sort || orderChanged) this.trigger('sort', this, options);
      }

      // Return the added (or merged) model (or models).
      return singular ? models[0] : models;
    },
```

**Comment by elgubenis** [comment] 2015-07-13 04:23
there is no request in #3700 for returning the models which were merged, but i think it might be a good moment/way to introduce that "info" in the same manner as previousModels is returned by the .reset method.

**Comment by elgubenis** [comment] 2015-07-13 04:35
this is the example to replicate the behavior, in this example 100 times the following code would be ran, even if there is no change to any model at all.
```javascript
attrs = this._isModel(attrs) ? attrs.attributes : attrs;
            if (options.parse) attrs = existing.parse(attrs, options);
            existing.set(attrs, options);
            if (sortable && !sort && existing.hasChanged(sortAttr)) sort = true;
            //mergedModels.push(existing);
```

```html
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="../backbone.js"></script>
  </head>
  <body>
    <script>
      $(document).ready(function() {
        var Collection = Backbone.Collection.extend({
          initialize: function() {
            this.listenTo(this, 'update', this._onCollectionUpdate);
          },
          _onCollectionUpdate: function() {
            console.log(arguments);
          }
        });
        var modelsArray = [];
        var objectsArray = [];
        for (var i = 0; i<100; i++) {
          var model = new Backbone.Model({
            id: i,
            name: 'Linus'
          });
          modelsArray.push(model);

          objectsArray.push({
            id: i,
            name: 'Linus'
          })
        }
        window.collection = new Collection(modelsArray);
        window.collection.set(objectsArray);
      });
    </script>
  </body>
</html>
```

**Comment by elgubenis** [comment] 2015-07-13 14:23
do you think its not a problem and i should move along? :disappointed:

**Comment by jridgewell** [comment] 2015-07-13 14:30
> 1. (overhead) 50 objects would get merged into 50 models which are already alike (dont need to get merged)
2. adding feedback/resume to the update event (see #3700) including mergedModels would return that there was a merge done on 50 models which were already alike.

There's no way for us to know wether the two objects are alike without parsing and setting. Keep in mind, `#set` may be overridden with custom code.

**Comment by elgubenis** [comment] 2015-07-13 14:39
the 2 bare attribute objects could be deepEqualed before, without taking into account order/sorting of keys, not sure if that might be even more expensive, i'd guess it depends alot on the size of the objects :facepunch:.

**Comment by jridgewell** [comment] 2015-07-13 14:54
`#set` can be overridden, there's no way to know what the new `attributes` object will morph into until it's called.

```js
class Model extends Backbone.Model {
  set: (attrs, options) {
    if (attrs.property) {
      attrs.property = customFunction(attrs.property);
    }
  }
}
```

**Closed by jridgewell** 2015-07-13 14:54 UTC

**Comment by akre54** [comment] 2015-07-13 15:52
Keep in mind that `attrs` can also be a Backbone model instance `collection.set([model1, model2])` and thus `collection.get(model1) === model1`.

**Comment by elgubenis** [comment] 2015-07-13 15:54
yeah, i had that in mind, i was only thinking about the case setting bare objects, not models, when setting models everything works as i would expect.

**Comment by elgubenis** [comment] 2015-08-19 16:21
hey, this got fixed.. i like that, even though it got closed by you before @jridgewell :disappointed:
