### ISSUE TITLE
Implement own method to sort collection

### ISSUE THREAD

**Issue by estshy** [jashkenas/backbone#4066] opened 2016-08-16 07:31 UTC
According to the codebase we sort collection using Array.prototype.sort which is not guaranteed to use stable sort algorithm. It leads to problems in Chrome while sorting table column with only empty values. 

Codebase:
```
   sort: function(options) {
      var comparator = this.comparator;
      if (!comparator) throw new Error('Cannot sort a set without a comparator');
      options || (options = {});

      var length = comparator.length;
      if (_.isFunction(comparator)) comparator = _.bind(comparator, this);
      if (length === 1 || _.isString(comparator)) {
        this.models = this.sortBy(comparator);
      } else {
        this.models.sort(comparator); //unstable Array.prototype.sort
      }
      if (!options.silent) this.trigger('sort', this, options);
      return this;
    },
```

Example test case:
```
Array(1000).fill(1).map(function(item, index) { return {id: index, n: ''} }).sort(function() { return 0 })
```

**Comment by akre54** [comment] 2016-08-16 16:26
Dupe of #3552.

Short of rewriting the browser's sort algorithm (which we really shouldn't do) I don't see much Backbone can do to handle this for you. If you really can't rely on your sort column (or can't do a second-order sort), you might want to drop in your own sort implementation.

**Closed by akre54** 2016-08-16 16:26 UTC
Labels: duplicate
