### ISSUE TITLE
Why removed require('jquery');?

### ISSUE THREAD

**Issue by martinoppitz** [jashkenas/backbone#3581] opened 2015-04-28 13:48 UTC
**It is required!**

```javascript
// Next for Node.js or CommonJS. jQuery may not be needed as a module.
  } else if (typeof exports !== 'undefined') {
    var _ = require('underscore');
    var $ = require('jquery');
    factory(root, exports, _, $);
```

**Comment by Florian-R** [comment] 2015-04-28 13:56
#2862 and #3528 IIRC

**Comment by jridgewell** [comment] 2015-04-28 14:13
Dupe of #2862.

**Closed by jridgewell** 2015-04-28 14:13 UTC

**Comment by martinoppitz** [comment] 2015-04-28 16:27
Sorry but that is not a solution for Backbone Marionette. Try it by yourself. 

npm install backbone.marionette

note: in my case the backbone dep was not installed automatically. Lookup before use. 

So. Ich used var Marionette = require(back... mario...);

Backbone.$ undefined. 

Why is the factory call in Backbone. Js in exports case different to requirejs and global? 

Where are the mistake? 

Backbonejs or Backbone.Marionette

**Comment by jridgewell** [comment] 2015-04-28 16:29
Latest Backbone (v1.1.2) doesn't have the require. It's fixed on master, and will be in the next release.

**Comment by martinoppitz** [comment] 2015-04-28 16:32
Top. That's is it!

**Comment by martinoppitz** [comment] 2015-04-28 16:33
I would like to make a code copy  for my comment  and I was very surprised, that is currently changed. Thanks

**Comment by mr47** [comment] 2015-04-28 16:43
For now you can try ''' Bower install'''  it have correct version,  and some times users npm for frontend libs cause same error. Or you can use git repo directly in your package.json for New.
