### ISSUE TITLE
Object.prototype properties conflict with `_.defaults`

### ISSUE THREAD

**Issue by qbolec** [jashkenas/backbone#3842] opened 2015-10-29 19:03 UTC
I run into an issue today, as Firefox added support for a new `watch` function to each Object.prototype, while I was unfortunate to use 'watch' as a name of an attribute of my Model.
The problem is caused by Model's constructor line:
```
attrs = _.defaults({}, attrs, _.result(this, 'defaults'));
```
and the fact that lodash's _.defaults implementation sees that `typeof {}.watch` is not `'undefined` so it does not want to override it with the one found in `attrs`.
Not sure if the issue is with Backbone, Lodash, or Firefox, but one thing is sure: while I can (and do) avoid today's magic properties (like `constructor`, `valueOf` etc.) I can not really anticipate what word will be forbiden in future, and don't like the idea of updating my app in future whenever one of my favorite words get's banned.

**Comment by jridgewell** [comment] 2015-10-29 19:14
Ooo, good find.

**Comment by akre54** [comment] 2015-10-29 19:27
Dupe of #1495?

**Comment by jridgewell** [comment] 2015-10-29 19:30
Nope, this isn't about `#get` or `#has`, but setting the attributes during construction:

```js
var Model = function(attrs) {
  //...
  attrs = _.defaults({}, attrs, _.result(this, 'defaults'));
};

var m = new Model({ hasOwnProperty: 'test' });
m.attributes.hasOwnProperty === 'test'; // => false
```

**Comment by akre54** [comment] 2015-10-29 19:31
Right, but it's related. The "don't name your keys `watch`" seems pretty related.

**Comment by akre54** [comment] 2015-10-29 19:35
```js
var model = new (Backbone.Model.extend({
  defaults: {
    watch: true
  }
}));
console.log(typeof model.attributes.watch); // boolean in chrome, function in FF
```

**Comment by jridgewell** [comment] 2015-10-29 19:38
> The "don't name your keys watch" seems fairly prescient.

Our creating a Model with arbitrary keys shouldn't be at the mercy of the runtime and our use of `_.defaults`.

> Right, but it's related.

Related, but only slightly. The other issues are for conflicts with properties that you don't define, this one prevents you from creating a model with any of the "reserved" properties.

**Comment by megawac** [comment] 2015-10-29 19:42
Yeah I agree with Justin and would consider this a bug

**Comment by akre54** [comment] 2015-10-29 19:43
Aside from [using `Object.create(null)` all over the place](https://github.com/paulmillr/exoskeleton/commit/444d8b918fa6fe10045ddb17a331013f836c68af#diff-3f8a8413d4465f6f1ed0cbb14f0b20a2L480) (which [comes with its own can of worms](https://github.com/paulmillr/exoskeleton/issues/84)) what would you propose we do?

**Comment by jridgewell** [comment] 2015-10-29 19:47
`_.extend`. We only use `_.defaults` 4 times, and most of them just need the argument orders adjusted.

```js
attrs = _.defaults({}, attrs, _.result(this, 'defaults'));
// ->
attrs = _.extend({}, _.result(this, 'defaults'), attrs);

**Comment by akre54** [comment] 2015-10-29 19:53
This feels like a half-solution (and drops readability down some), but fine, go for it.

I still think you should avoid `watch`, `toString`, `constructor` et al in your app, at least for now.

**Comment by jdalton** [comment] 2015-10-29 20:06
You could modify the `defaults `check to not skip if the value `===` those on the `Object.prototype`. Firefox is experimenting with making the `Object.prototype` non-writable.

**Comment by jdalton** [comment] 2015-10-29 20:32
I wouldn't classify this as a bug as `_.defaults` is behaving by design. If anything the request would be an enhancement or change.

**Comment by akre54** [comment] 2015-10-29 20:36
Changing this will introduce a subtle bug in any apps that relied on the behavior of `defaults` with `undefined`. Let's tread carefully.

**Comment by jdalton** [comment] 2015-10-29 20:43
It wouldn't effect the `undefined` case. As `defaults` behavior is to assign on `undefined` so even if an `Object.prototype` value exists but has an `undefined` value it will still assign. The change to allow assigning for values that `===` those on the `Object.prototype` object won't effect that.

**Comment by jdalton** [comment] 2015-10-29 20:45
Smth like:
```
if (!defaults || (obj[key] === void 0 || obj[key] === Object.prototype[key])) obj[key] = source[key];
```
or you could get more complex and check if a key exists on the `Object.prototype if there's a match.

**Comment by akre54** [comment] 2015-10-29 20:55
@jdalton what do you mean? I'm referring to this case:

```js
var Model = Backbone.Model.extend({
  defaults: {
    foo: true
  }
});

var model = new Model({foo: undefined});

// with _.defaults:
model.get('foo'); // true

// with _.extend:
model.get('foo'); // undefined
```

**Comment by megawac** [comment] 2015-10-29 20:58
_.extend would preserve undefined Adam. Model.extend differs in semantics
from _.extend

_.extend({}, {foo: undefined})
_.defaults({}, {foo: undefined})

**Comment by jdalton** [comment] 2015-10-29 21:02
@akre54 
> what do you mean?

I'm referring to `_.defaults`.

**Comment by akre54** [comment] 2015-10-29 21:05
@megawac  I'm aware :expressionless:

I'm referring to [this line]()https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L401).

```js
var defaults = {foo: true};
var attrs = {foo: undefined};
_.extend({}, defaults, attrs); // {foo: undefined}
_.defaults({}, attrs, defaults); // {foo: true}
```

**Comment by jridgewell** [comment] 2015-10-29 22:08
How about checking the source value for `undefined` instead of the destination value in `_.defualts`?

**Comment by qbolec** [comment] 2015-10-30 09:42
Well, that escalated quickly!
I was expecting some simple solution like `Object.hasOwnProperty` to be used.
Why would `hasOwnProperty` be a bad solution?
The only reason I could come up with is that you want to support use cases in which the developer intentionally creates some prototype chains, and he really wants this inherited properties to be assigned as attributes (that would be a bit strange to me, as usually the things I'm most interested in inherting from the prototype are methods, not fields, and I would not like to treat them as attributes of the model).

So perhaps the thing I'd really like to use is `Object.propertyIsEnumerable`, and let the developer decide which of the many properties (inherited or not) are those he want to treat as attributes.

A third approach is perhaps stupid, but ... if we really want to treat all fields (even those with `!hasOwnProperty(x)` and those with `propertyIsEnumerable(x)`) as worth being an attribute, then we have to have some criterion to decide if we prefer a value from `this.defaults()` or from the argument passed to constructor - intuitively it should match the developer's intent that if he specified the attribute explicitly for the constructor argument then it should be used. This leads to a following idea: let us traverse the prototype chains of `defaults` and `attrs` and find the Lowest Common Ancestor, and compare values of fields against the values in the LCA with `===`. 
```
if( attr[x] === defaults[x]){  //easy case: 
   result[x] = attr[x];
}else if(attr[x] === lca[x]) { //defaults has a "fresh" (not inherited) value
  result[x] = defaults[x];
}else{ //both attr and defaults have "fresh" values, so we tie-break by prefering attr[x]
  result[x] = attr[x];
}
```

**Comment by qbolec** [comment] 2015-10-30 09:46
After reading the code again I'm a bit puzzled: the merging uses a for..in loop, which by definition iterates only fields which have `propertyIsEnumerable(x)`, (and certainly the `watch` function has it set to `false`) so the only reason we get the conflict is because we do not check for propertyIsEnumerable in all objects, just in the one (implicitly) we are iterating over.

**Closed** 2016-02-04 17:23 UTC
Labels: bug
